### PR TITLE
adjust build

### PR DESCRIPTION
**Pull request by BusyJay**
So that we can call `cmake::Build().register_dep("LZ4")`.

### CODE REVIEW

**Comment by bozaro** [comment]
What is the reason of the first change?

**Comment by BusyJay** [comment]
rust-rocksdb wants to build rocksdb using cmake, and I want to let it auto-detect the lz4 library. To make it work, lz4's build script needs to output a metadata `cargo:root`, which will be passed to rust-rocksdb's build script and used by cmake-rs.
For more information, you can see the explanation in http://doc.crates.io/build-script.html#outputs-of-the-build-script.

**Comment by jheyens** [comment]
Is this still wanted?
If yes, I would need a better explanation, since printing `cargo:root{..}` isn't the only addition to `build.rs`

**Comment by jheyens** [comment]
I've been thinking about this and decided I'm going to merge this under the following conditions:
 
 * The modified build.rs needs to be hidden behind a feature flag
 * The feature flag must be documented and explained in the Readme file (An example showing how and why this could be useful would be nice)
 * The code should be documented, since it is non-obvious, even though it's only a few lines
 * We need a test case that it works as expected for the CI
 * Without specifying the feature flag, behaviour must not differ from what it is now.

Sorry this took that long, but I haven't really used CMake yet and even now I'm not sure why this isn't a problem with CMake itself.

**Comment by benesch** [comment]
Not the author, but I would really like this too!

> Sorry this took that long, but I haven't really used CMake yet and even now I'm not sure why this isn't a problem with CMake itself.

It's not really related to CMake at all, actually. It's about the responsibilities of a *-sys crate. *-sys crates are supposed to make it possible for downstream dependencies to locate the library that the *-sys crate has compiled. Printing `cargo:rustc-link-search=blah` makes it possible for rustc to find the compiled artifacts, but not for other crates to find the artifacts. (The CC crate does this [printing for lz4-sys](https://github.com/alexcrichton/cc-rs/blob/0eeafcc903059507f1e5a2ef2c2cb008cce26b02/src/lib.rs#L831-L840) automatically right now.)  If RocksDB were instead using autotools, or a handwritten Makefile, it would still need a `DEP_LZ4_ROOT` variable to know where to find the lz4 library that lz4-sys compiled.

I'd like to recommend that this *not* be behind a feature flag. IMO this is something that should be provided unconditionally, because it won't impact any current users and will enable any new users to easily plug in a downstream build system.

**Comment by jheyens** [comment]
I accept your reasoning. I'll merge this, but this won't be pushed onto crates.io until early November.

**Comment by benesch** [comment]
> I accept your reasoning. I'll merge this, but this won't be pushed onto crates.io until early November.

Awesome, thanks! Much appreciated.

> Build scripts that may panic should be refactored. Don't unwrap().

Ok, I can whip up a PR for that. You just want an `eprintln!` and `process::exit(1)` instead?

**Comment by jheyens** [comment]
Yes.

**Comment by benesch** [comment]
As promised: #44

**Comment by benesch** [comment]
Hi, @jheyens, any update on getting a release out to crates.io?

**Pull request merged**
